from enum import Enum


class BuiltinFn(Enum):
    ABORT = "abort"
    ASSERT = "assert"
    CPROVER_ASSUME = "__CPROVER_assume"
    CPROVER_COVER = "__CPROVER_cover"
    CALLOC = "calloc"
    CEIL = "ceil"
    CEILF = "ceilf"
    COPYSIGN = "copysign"
    COPYSIGNF = "copysignf"
    COS = "cos"
    COSF = "cosf"
    ERROR = "__error"
    ERROR_NO_LOCATION = "__errno_location"
    EXP = "exp"
    EXP2 = "exp2"
    EXP2F = "exp2f"
    EXPF = "expf"
    FABS = "fabs"
    FABSF = "fabsf"
    FLOOR = "floor"
    FLOORF = "floorf"
    FMA = "fma"
    FMAF = "fmaf"
    FMAX = "fmax"
    FMAXF = "fmaxf"
    FMIN = "fmin"
    FMINF = "fminf"
    FREE = "free"
    LOG = "log"
    LOG10 = "log10"
    LOG10F = "log10f"
    LOG2 = "log2"
    LOG2F = "log2f"
    LOGF = "logf"
    MALLOC = "malloc"
    MEMCMP = "memcmp"
    MEMCPY = "memcpy"
    MEMMOVE = "memmove"
    MEMSET = "memset"
    NEARBYINT = "nearbyint"
    NEARBYINTF = "nearbyintf"
    POSIXMEMALIGN = "posix_memalign"
    POW = "pow"
    POWF = "powf"
    POWI = "__builtin_powi"
    POWIF = "__builtin_powif"
    REALLOC = "realloc"
    RINT = "rint"
    RINTF = "rintf"
    ROUND = "round"
    ROUNDF = "roundf"
    SIN = "sin"
    SINF = "sinf"
    SQRT = "sqrt"
    SQRTF = "sqrtf"
    SYSCONF = "sysconf"
    TRUNC = "trunc"
    TRUNCF = "truncf"
    UNLINK = "unlink"

    def __str__(self):
        return self.value


# Example usage:
print(BuiltinFn.CEIL)  # Output: ceil
print(str(BuiltinFn.POWI))  # Output: __builtin_powi
